Io 4782 add mail api docs
iOffice/ioffice.github.io pull request #15
Opened 2018-05-24 21:43 UTC by GimmeYerGold

CHANGES

• Added all of the Mail Endpoints I could find! (a lot!)

https://ioffice.myjetbrains.com/youtrack/issue/io-4782

2018-05-25 19:08 UTC, quesojean requested changes
this is what i have so far...looks great, thank you!

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> +    + commentBy (string, `Hank`) ... author noteg to accompany new comment for the Mail Item
noteg correct spelling

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> +    + commentBy (string, `Hank`) ... author noteg to accompany new comment for the Mail Item
commentBy is not required.  If it is missing will use either the logged in user and if no authenticated user, will simply use "3rd Party"

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> +Collection of all Mail Routes.
Collection of all Mail Locations

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> +## Mail Items Collection [/mail/items]
not sure if you want a separate entry or add optional request parameter to this endpoint, but we need to document searching mail endpoint (hits both mail and archived mail items):
will search id, trackingNumber, & originalTrackingNumber fields
mail/items?search=<text>

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> +### Deliver a Mail Item [PUT]
shouldnt we document optional properties as well?
SignatureData

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> ++ Parameters
also, need to include batch deliver endpoint (PUT takes a Seq of DeliverData- see MailItemResource)

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> +### Check In a Mail Item [POST]
there is also a batch checkin post endpoint that takes a collection of mail items.
mail/items/checkin

I believe to checkin a single mail item, its simply a POST /mail/item with the mail json body

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> +### Pend a Mail Item [PUT]
please document optional property as well pendingDate

2018-05-25 19:08 UTC, quesojean commented on api/endpoints/mail.md
> ++ Parameters
document optional  checkoutDate property

2018-06-04 15:31 UTC, quesojean approved these changes

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> +### Deliver a Mail Item [PUT]
🎏 passing on optional properties for this PR 🎏

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> ++ Parameters
🎏 passing on optional properties for this PR 🎏

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> +### Pend a Mail Item [PUT]
🎏 passing on optional properties for this PR 🎏

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> +    + commentBy (string, `Hank`) ... author noteg to accompany new comment for the Mail Item
✅

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> +    + commentBy (string, `Hank`) ... author noteg to accompany new comment for the Mail Item
✅

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> +Collection of all Mail Routes.
✅

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> +## Mail Items Collection [/mail/items]
✅

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> +### Check In a Mail Item [POST]
✅

2018-06-04 15:36 UTC, GimmeYerGold commented on api/endpoints/mail.md
> ++ Parameters
✅

2018-06-04 15:44 UTC, merged