Adding missing params
iOffice/ioffice.github.io pull request #4
Opened 2016-10-20 18:19 UTC by GimmeYerGold

@kentongray Lemme know if I missed anything. From here I'll move ahead with displaying better request examples.

2016-10-20 19:38 UTC, rmoscowitz requested changes

2016-10-20 19:38 UTC, rmoscowitz commented on api/endpoints/reservation.md
> +    + roomId (optional, number, `16`) ... Id of the room to query from
Can you double check these? I think these are `building`/`room`, not `buildingId`/`roomId`.

2016-10-20 19:38 UTC, rmoscowitz commented on api/endpoints/room.md
>      + search (optional, string, `conference`) ... String to search for room by name
`search` is in the list of global options; should it also be here?

2016-10-20 19:38 UTC, rmoscowitz commented on api/endpoints/room.md
>  + Parameters
Should the `## Room Collection...` line above be updated with the new params too?

2016-10-20 19:38 UTC, rmoscowitz commented on api/endpoints/user.md
>      + search (optional, string, `mario`) ... String to search for user by firstName, lastName, or email
`search` is in the list of global options; should it also be here?

2016-10-20 19:38 UTC, rmoscowitz commented on api/endpoints/user.md
> -
Also `usertypeid` (int)

2016-10-20 19:38 UTC, rmoscowitz commented on api/endpoints/user.md
The last section of this file... I'm not sure what that is...

```
 ### Hold a Request [GET]
 + Response 200
     [User][]
```

It also looks like there are some things in `UserResource.scala` that aren't in this file yet:
```
/me/reportAuth
/me/supportAuth
/{id}/resetPassword
/{id}/resetPassword
/{id}/permissions GET & PUT
{id}/attachAvatar
username/{username}
```

2016-11-14 22:35 UTC, GimmeYerGold commented
@rmoscowitz okay, I think I addressed all your comments, but let me know if there are any other edits needed. Thanks!

2016-11-15 16:26 UTC, GimmeYerGold commented
@rmoscowitz @kentongray added one more edit per Nate's request: change 'Remove a Request' to 'Cancel a Request' for more customer clarity

2016-11-15 21:33 UTC, jmlopez-rod commented
Don't forget to generate the html file.

2016-11-15 21:44 UTC, GimmeYerGold commented
@jmlopez-rod okay, just did a commit with the index file. Thanks!

2016-11-15 21:45 UTC, jmlopez-rod requested changes

2016-11-15 21:45 UTC, jmlopez-rod commented on api/endpoints/user.md
> +    + userTypeId (optional, number, `23`) ... If of user type to query from.
`If`? you mean `Id`?

2016-11-15 21:45 UTC, jmlopez-rod commented on api/endpoints/user.md
> +            [
Can you reformat this json block? https://jsonformatter.curiousconcept.com/

2016-11-15 22:21 UTC, GimmeYerGold commented
@jmlopez-rod next round of edits done !

2016-11-15 22:24 UTC, jmlopez-rod approved these changes

2016-11-16 16:06 UTC, rmoscowitz commented on api/endpoints/user.md
> +                "username: "foxmccloud"
Can we use fake info here?

2016-11-16 16:06 UTC, rmoscowitz commented on api/endpoints/user.md
> +                "authToken:" "imp_46436454_3452345345dgdg3q5345dsgdgsdg_=dev_fmccloud_420"
Same question here, can this be fake data instead?

2016-11-16 16:06 UTC, rmoscowitz commented on api/endpoints/user.md
> +            [
Also, can we change some of the roles to show examples of the other roles?

2016-11-16 16:06 UTC, rmoscowitz commented on api/endpoints/user.md
Two still missing, I think:

```
/{id}/permissions PUT
{id}/attachAvatar
```

2016-11-17 22:27 UTC, GimmeYerGold commented on api/endpoints/user.md
> +                "username: "foxmccloud"
@rmoscowitz lol i thought this was fake 😄 I just typed a bunch of random stuff for authToken, and followed the Starfox references for the other stuff, including the server name.

2016-11-23 19:02 UTC, GimmeYerGold commented
@rmoscowitz okee dokee, i think I got the rest of your comments on here :)

2016-11-23 21:08 UTC, rmoscowitz approved these changes

2016-11-23 21:10 UTC, merged